name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: npm install
  displayName: 'npm install'

- script: yarn build-production
  displayName: 'yarn build'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: build
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
